apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis
    imagePullPolicy: IfNotPresent
    args:
    - "--port"
    - "6889"
    - "--requirepass"
    - "293r9vfT7dfa&^"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
  - port: 6889
  selector:
    app: redis
  externalIPs:
    - "10.0.0.100" # available both in pod network and node network
---
apiVersion: v1
kind: Secret
metadata:
  name: spilot-redis-config
type: Opaque
stringData:
  redis-host: "10.0.0.100"
  redis-port: "6889"
  redis-password: "293r9vfT7dfa&^"