name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout code
        uses: taiki-e/checkout-action@v1

      - name: Remove old dist files
        run: |
          if [ -d "dist" ]; then
            rm -rf dist/*
          fi

      - name: Build package
        run: |
          python3 setup.py bdist_wheel

      - name: Deploy to local PyPI
        run: |
          twine upload --repository-url http://localhost:12121/ dist/* -u "faasit" -p "faasit-pypi" --verbose
